export const USER_EMAIL_STORAGE_KEY = "userEmail";
export const AMBASSADOR_STORAGE_KEY = "ambassador";
export const PAYMENT_VALUE_CAMPAIGNID_STORAGE_KEY = "payment";
export const AMBASSADOR_IS_EDITTING = "ambassadorEditting";
export const FAIL_LOGIN = "Falha ao entrar!";
export const FAIL_SIGN_UP = "Falha ao realizar cadastro!";
export const TOAST_DURATION = 6000;
export const MAX_PHOTO_SIZE_IN_MB = 11;

export const SCHOOLING = [
  "Não-escolarizado",
  "Ensino Fundamental",
  "Ensino Médio",
  "Ensino Superior",
  "Múltiplas Graduações",
  "Especialização",
  "Mestrado",
  "Doutorado",
  "Pós-doutorado",
];

export const COUNTRIES = [
  "Afeganistão",
  "África do Sul",
  "Albânia",
  "Alemanha",
  "Andorra",
  "Angola",
  "Anguilla",
  "Antilhas Holandesas",
  "Antárctida",
  "Antígua e Barbuda",
  "Argentina",
  "Argélia",
  "Armênia",
  "Aruba",
  "Arábia Saudita",
  "Austrália",
  "Áustria",
  "Azerbaijão",
  "Bahamas",
  "Bahrein",
  "Bangladesh",
  "Barbados",
  "Belize",
  "Benim",
  "Bermudas",
  "Bielorrússia",
  "Bolívia",
  "Botswana",
  "Brasil",
  "Brunei",
  "Bulgária",
  "Burkina Faso",
  "Burundi",
  "Butão",
  "Bélgica",
  "Bósnia e Herzegovina",
  "Cabo Verde",
  "Camarões",
  "Camboja",
  "Canadá",
  "Catar",
  "Cazaquistão",
  "Chade",
  "Chile",
  "China",
  "Chipre",
  "Colômbia",
  "Comores",
  "Coreia do Norte",
  "Coreia do Sul",
  "Costa do Marfim",
  "Costa Rica",
  "Croácia",
  "Cuba",
  "Dinamarca",
  "Djibouti",
  "Dominica",
  "Egito",
  "El Salvador",
  "Emirados Árabes Unidos",
  "Equador",
  "Eritreia",
  "Escócia",
  "Eslováquia",
  "Eslovênia",
  "Espanha",
  "Estados Federados da Micronésia",
  "Estados Unidos",
  "Estônia",
  "Etiópia",
  "Fiji",
  "Filipinas",
  "Finlândia",
  "França",
  "Gabão",
  "Gana",
  "Geórgia",
  "Gibraltar",
  "Granada",
  "Gronelândia",
  "Grécia",
  "Guadalupe",
  "Guam",
  "Guatemala",
  "Guernesei",
  "Guiana",
  "Guiana Francesa",
  "Guiné",
  "Guiné Equatorial",
  "Guiné-Bissau",
  "Gâmbia",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungria",
  "Ilha Bouvet",
  "Ilha de Man",
  "Ilha do Natal",
  "Ilha Heard e Ilhas McDonald",
  "Ilha Norfolk",
  "Ilhas Cayman",
  "Ilhas Cocos (Keeling)",
  "Ilhas Cook",
  "Ilhas Feroé",
  "Ilhas Geórgia do Sul e Sandwich do Sul",
  "Ilhas Malvinas",
  "Ilhas Marshall",
  "Ilhas Menores Distantes dos Estados Unidos",
  "Ilhas Salomão",
  "Ilhas Virgens Americanas",
  "Ilhas Virgens Britânicas",
  "Ilhas Åland",
  "Indonésia",
  "Inglaterra",
  "Índia",
  "Iraque",
  "Irlanda do Norte",
  "Irlanda",
  "Irã",
  "Islândia",
  "Israel",
  "Itália",
  "Iêmen",
  "Jamaica",
  "Japão",
  "Jersey",
  "Jordânia",
  "Kiribati",
  "Kuwait",
  "Laos",
  "Lesoto",
  "Letônia",
  "Libéria",
  "Liechtenstein",
  "Lituânia",
  "Luxemburgo",
  "Líbano",
  "Líbia",
  "Macau",
  "Macedônia",
  "Madagáscar",
  "Malawi",
  "Maldivas",
  "Mali",
  "Malta",
  "Malásia",
  "Marianas Setentrionais",
  "Marrocos",
  "Martinica",
  "Mauritânia",
  "Maurícia",
  "Mayotte",
  "Moldávia",
  "Mongólia",
  "Montenegro",
  "Montserrat",
  "Moçambique",
  "Myanmar",
  "México",
  "Mônaco",
  "Namíbia",
  "Nauru",
  "Nepal",
  "Nicarágua",
  "Nigéria",
  "Niue",
  "Noruega",
  "Nova Caledônia",
  "Nova Zelândia",
  "Níger",
  "Omã",
  "Palau",
  "Palestina",
  "Panamá",
  "Papua-Nova Guiné",
  "Paquistão",
  "Paraguai",
  "País de Gales",
  "Países Baixos",
  "Peru",
  "Pitcairn",
  "Polinésia Francesa",
  "Polônia",
  "Porto Rico",
  "Portugal",
  "Quirguistão",
  "Quênia",
  "Reino Unido",
  "República Centro-Africana",
  "República Checa",
  "República Democrática do Congo",
  "República do Congo",
  "República Dominicana",
  "Reunião",
  "Romênia",
  "Ruanda",
  "Rússia",
  "Saara Ocidental",
  "Saint Martin",
  "Saint-Barthélemy",
  "Saint-Pierre e Miquelon",
  "Samoa Americana",
  "Samoa",
  "Santa Helena, Ascensão e Tristão da Cunha",
  "Santa Lúcia",
  "Senegal",
  "Serra Leoa",
  "Seychelles",
  "Singapura",
  "Somália",
  "Sri Lanka",
  "Suazilândia",
  "Sudão",
  "Suriname",
  "Suécia",
  "Suíça",
  "Svalbard e Jan Mayen",
  "São Cristóvão e Nevis",
  "São Marino",
  "São Tomé e Príncipe",
  "São Vicente e Granadinas",
  "Sérvia",
  "Síria",
  "Tadjiquistão",
  "Tailândia",
  "Taiwan",
  "Tanzânia",
  "Terras Austrais e Antárticas Francesas",
  "Território Britânico do Oceano Índico",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Toquelau",
  "Trinidad e Tobago",
  "Tunísia",
  "Turcas e Caicos",
  "Turquemenistão",
  "Turquia",
  "Tuvalu",
  "Ucrânia",
  "Uganda",
  "Uruguai",
  "Uzbequistão",
  "Vanuatu",
  "Vaticano",
  "Venezuela",
  "Vietname",
  "Wallis e Futuna",
  "Zimbabwe",
  "Zâmbia",
];

export const STATES = [
  "Acre",
  "Alagoas",
  "Amapá",
  "Amazonas",
  "Bahia",
  "Ceará",
  "Distrito Federal",
  "Espírito Santo",
  "Goiás",
  "Maranhão",
  "Mato Grosso",
  "Mato Grosso do Sul",
  "Minas Gerais",
  "Pará",
  "Paraíba",
  "Paraná",
  "Pernambuco",
  "Piauí",
  "Rio de Janeiro",
  "Rio Grande do Norte",
  "Rio Grande do Sul",
  "Rondônia",
  "Roraima",
  "São Paulo",
  "Santa Catarina",
  "Sergipe",
  "Tocantins",
  "Estrangeiro",
];
